# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AtamFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


###### 메모장########
import os






class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(928, 839)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 120, 81, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(170, 70, 81, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 170, 81, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 120, 81, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(40, 70, 81, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 170, 81, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(110, 220, 81, 23))
        self.pushButton.setObjectName("pushButton")
        
        self.verticalLayout_3.addWidget(self.frame)
        
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_5.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        
        self.gridLayout_5.addWidget(self.frame_2, 0, 0, 1, 1)
        
        self.horizontalLayout_2.addLayout(self.gridLayout_5)
        self.horizontalLayout_2.setStretch(0, 100)
        self.horizontalLayout_2.setStretch(1, 200)
        
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_12.setObjectName("gridLayout_12")
        
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        
        self.gridLayout_12.addWidget(self.frame_3, 0, 0, 1, 1)
        
        self.horizontalLayout_3.addLayout(self.gridLayout_12)
        
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 100, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_10.setGeometry(QtCore.QRect(150, 100, 196, 23))
        self.pushButton_10.setMinimumSize(QtCore.QSize(196, 0))
        self.pushButton_10.setObjectName("pushButton_10")
        #
        self.pushButton_10.clicked.connect(self.note)
        
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_8.setGeometry(QtCore.QRect(390, 100, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        
        self.horizontalLayout_4.addWidget(self.frame_4)
        
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.setStretch(0, 100)
        self.horizontalLayout_3.setStretch(1, 200)
        
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 21))
        self.menubar.setObjectName("menubar")
        
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "요구사항 5"))
        self.pushButton_4.setText(_translate("MainWindow", "요구사항 4"))
        self.pushButton_5.setText(_translate("MainWindow", "요구사항 3"))
        self.pushButton_6.setText(_translate("MainWindow", "요구사항 2"))
        self.pushButton_7.setText(_translate("MainWindow", "요구사항 1"))
        self.pushButton_2.setText(_translate("MainWindow", "요구사항 6"))
        self.pushButton.setText(_translate("MainWindow", "요구사항 7"))
        self.pushButton_9.setText(_translate("MainWindow", "cmd"))
        self.pushButton_10.setText(_translate("MainWindow", "메모장"))
        self.pushButton_8.setText(_translate("MainWindow", "Chrome"))
        self.menu.setTitle(_translate("MainWindow", "설정"))
        
    def note(self, MainWindow):
        self.pushButton_10.clicked.connect(os.system('notepad.exe'))
        
        
    #def promt(self, MainWindow):
        #file = "cmd.exe"
        #self.pushButton_2.clicked.connect(os.system(file))
         
    #def brows(self, MainWindow):
        #self.pushButton_3.clicked.connect(os.system('chrome.exe'))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
  
    
    
    

    
    
